import { getTestBed } from "@angular/core/testing";
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting,
} from "@angular/platform-browser-dynamic/testing";
import { loadSpecs } from "./spec-manifest";

// Unfortunately there's no typing for the `__karma__` variable. Just declare it as any.
declare const __karma__: any;

// Prevent Karma from running prematurely.
__karma__.loaded = function () {};

// First, initialize the Angular testing environment.
getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting()
);

// Load every spec file. The manifest is regenerated by test-setup.js during
// `npm run init` from the actual .spec.ts files on disk, so adding a spec
// automatically registers it — no manual list to maintain here.
//
// Note: require.context was avoided because webpack's eager bundle compilation
// for the full tree exceeds the karma browser-no-activity timeout.
loadSpecs();

// Finally, start Karma to run the tests.
__karma__.start();
