const fs = require('fs');
const path = require('path');

var copyRecursiveSync = function(src, dest) {
    var exists = fs.existsSync(src);
    var stats = exists && fs.statSync(src);
    var isDirectory = exists && stats.isDirectory();
    if (exists && isDirectory) {
      fs.mkdirSync(dest);
      fs.readdirSync(src).forEach(function(childItemName) {
        copyRecursiveSync(path.join(src, childItemName),
                          path.join(dest, childItemName));
      });
    } else {
      fs.linkSync(src, dest);
    }
};

copyRecursiveSync('../src','./src/components');

// Generate a static spec manifest so every .spec.ts under src/components is
// automatically registered with Karma. This keeps the harness deterministic
// (require.context times out compiling the full tree) while ensuring a
// newly-added spec is never silently skipped.
var collectSpecs = function(dir, base) {
    var specs = [];
    fs.readdirSync(dir).forEach(function(name) {
        var full = path.join(dir, name);
        if (fs.statSync(full).isDirectory()) {
            specs = specs.concat(collectSpecs(full, base));
        } else if (/\.spec\.ts$/.test(name)) {
            var rel = path.relative(base, full).replace(/\\/g, '/').replace(/\.ts$/, '');
            specs.push('./' + rel);
        }
    });
    return specs.sort();
};

var specs = ['./app/app.component.spec'].concat(
    collectSpecs('./src/components', './src')
);

var manifest =
    '// AUTO-GENERATED by test-setup.js during `npm run init`. Do not edit by hand.\n' +
    '// Every .spec.ts under src/components is registered here so adding a spec\n' +
    '// automatically wires it into Karma.\n' +
    'declare const require: any;\n\n' +
    'export function loadSpecs(): void {\n' +
    specs.map(function(s) { return "  require('" + s + "');"; }).join('\n') +
    '\n}\n';

fs.writeFileSync('./src/spec-manifest.ts', manifest);
console.log('Generated spec-manifest.ts with ' + specs.length + ' spec files');
