name: Lint

on:
  pull_request:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: .nvmrc
      - name: Install root dependencies
        run: npm install --no-package-lock --ignore-scripts
      - name: Check formatting
        run: npm run format:check
      - name: Install test-app dependencies
        run: npm install --prefix test-app --no-package-lock
      - name: Lint library and documentation app
        run: npm run lint
      - name: Lint test app
        run: npm --prefix test-app run lint
